package ppio

const (
	TASK_STATUS_QUEUED     = "TASK_STATUS_QUEUED"
	TASK_STATUS_SUCCEED    = "TASK_STATUS_SUCCEED"
	TASK_STATUS_FAILED     = "TASK_STATUS_FAILED"
	TASK_STATUS_PROCESSING = "TASK_STATUS_PROCESSING"
)
